
format = '$directory($git_branch$git_status) '

right_format = '$c$rust$golang$python$nodejs'

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false

[directory]
format            = '[ $path ]($style)'
truncation_length = 3
truncate_to_repo  = true
style             = 'bg:blue fg:white'

[git_branch]
format ='[ $branch(:$remote_branch)]($style)'
style  = 'bg:yellow fg:black'

[git_status]
format   = '[$modified ]($style)'
style    = 'bg:yellow fg:black'
modified = '*'

[docker_context]
symbol = ''
style  = 'bg:#06969A fg:#DCE7E8'
format = '[ $symbol $context ]($style) $path'

[c]
symbol = ''
style  = 'bg:#86BBD8 fg:#DCE7E8'
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ''
style  = 'bg:#86BBD8 fg:#DCE7E8'
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = ''
style  = 'bg:#86BBD8 fg:#DCE7E8'
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ''
style  = 'bg:#86BBD8 fg:#DCE7E8'
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ''
style  = 'bg:#86BBD8 fg:#DCE7E8'
format = '[ $symbol ($version) ]($style)'
