# Custom Prompt Theme inspried by `BoxFish` OMF Theme

format       = '$character$directory($git_branch$git_status) '
right_format = '$c$rust$golang$python$nodejs$cmd_duration'

scan_timeout = 10
add_newline  = false

[cmd_duration]
format             = '[ time=$duration ]($style)'
min_time           = 5_000
show_notifications = true
style              = 'bg:white fg:black'

[character]
format         = '$symbol'
success_symbol = ''
error_symbol   = '[ ! ](bg:red fg:#DCE7E8)'

[directory]
format            = '[ $path ]($style)'
truncation_length = 3
truncate_to_repo  = true
style             = 'bg:blue fg:white'

[git_branch]
format ='[ $branch(:$remote_branch) ]($style)'
style  = 'bg:yellow fg:black'

[git_status]
format = '([$all_status$ahead_behind ]($style))'
style  = 'bg:yellow fg:black'

[docker_context]
symbol = ''
style  = 'bg:#06969A fg:#DCE7E8'
format = '[ $symbol $context ]($style) $path'

[c]
symbol = ''
style  = 'bg:#86BBD8 fg:#DCE7E8'
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ''
style  = 'bg:#86BBD8 fg:#DCE7E8'
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = ''
style  = 'bg:#86BBD8 fg:#DCE7E8'
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ''
style  = 'bg:#86BBD8 fg:#DCE7E8'
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ''
style  = 'bg:#86BBD8 fg:#DCE7E8'
format = '[ $symbol ($version) ]($style)'
